{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:17:58.214Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:17:58.214Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:17:58.214Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"model","msg":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","time":"2018-09-27T14:17:58.216Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"err":{"message":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","name":"Error","stack":"Error: DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred\n    at datastore.connect.then.catch.err (/home/dwd/code/mine/projectchaplin/api/node_modules/@dadi/api/dadi/lib/model/connection.js:111:27)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"msg":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","time":"2018-09-27T14:17:58.216Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:17:58.217Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"model","msg":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","time":"2018-09-27T14:17:58.217Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"err":{"message":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","name":"Error","stack":"Error: DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred\n    at datastore.connect.then.catch.err (/home/dwd/code/mine/projectchaplin/api/node_modules/@dadi/api/dadi/lib/model/connection.js:111:27)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"msg":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","time":"2018-09-27T14:17:58.217Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:17:58.218Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"model","msg":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","time":"2018-09-27T14:17:58.218Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"err":{"message":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","name":"Error","stack":"Error: DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred\n    at datastore.connect.then.catch.err (/home/dwd/code/mine/projectchaplin/api/node_modules/@dadi/api/dadi/lib/model/connection.js:111:27)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"msg":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","time":"2018-09-27T14:17:58.218Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:17:58.219Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"err":{"message":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","name":"Error","stack":"Error: DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred\n    at datastore.connect.then.catch.err (/home/dwd/code/mine/projectchaplin/api/node_modules/@dadi/api/dadi/lib/model/connection.js:111:27)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"msg":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","time":"2018-09-27T14:17:58.219Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"model","msg":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","time":"2018-09-27T14:17:58.216Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"err":{"message":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","name":"Error","stack":"Error: DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred\n    at datastore.connect.then.catch.err (/home/dwd/code/mine/projectchaplin/api/node_modules/@dadi/api/dadi/lib/model/connection.js:111:27)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"msg":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","time":"2018-09-27T14:17:58.216Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:17:58.217Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"model","msg":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","time":"2018-09-27T14:17:58.217Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"err":{"message":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","name":"Error","stack":"Error: DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred\n    at datastore.connect.then.catch.err (/home/dwd/code/mine/projectchaplin/api/node_modules/@dadi/api/dadi/lib/model/connection.js:111:27)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"msg":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","time":"2018-09-27T14:17:58.217Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:17:58.218Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"model","msg":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","time":"2018-09-27T14:17:58.218Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"err":{"message":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","name":"Error","stack":"Error: DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred\n    at datastore.connect.then.catch.err (/home/dwd/code/mine/projectchaplin/api/node_modules/@dadi/api/dadi/lib/model/connection.js:111:27)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"msg":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","time":"2018-09-27T14:17:58.218Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:17:58.219Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"err":{"message":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","name":"Error","stack":"Error: DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred\n    at datastore.connect.then.catch.err (/home/dwd/code/mine/projectchaplin/api/node_modules/@dadi/api/dadi/lib/model/connection.js:111:27)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"msg":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","time":"2018-09-27T14:17:58.219Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"model","msg":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","time":"2018-09-27T14:17:58.216Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"err":{"message":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","name":"Error","stack":"Error: DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred\n    at datastore.connect.then.catch.err (/home/dwd/code/mine/projectchaplin/api/node_modules/@dadi/api/dadi/lib/model/connection.js:111:27)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"msg":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","time":"2018-09-27T14:17:58.216Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:17:58.217Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"model","msg":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","time":"2018-09-27T14:17:58.217Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"err":{"message":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","name":"Error","stack":"Error: DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred\n    at datastore.connect.then.catch.err (/home/dwd/code/mine/projectchaplin/api/node_modules/@dadi/api/dadi/lib/model/connection.js:111:27)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"msg":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","time":"2018-09-27T14:17:58.217Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:17:58.218Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"model","msg":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","time":"2018-09-27T14:17:58.218Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"err":{"message":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","name":"Error","stack":"Error: DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred\n    at datastore.connect.then.catch.err (/home/dwd/code/mine/projectchaplin/api/node_modules/@dadi/api/dadi/lib/model/connection.js:111:27)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"msg":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","time":"2018-09-27T14:17:58.218Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:17:58.219Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"err":{"message":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","name":"Error","stack":"Error: DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred\n    at datastore.connect.then.catch.err (/home/dwd/code/mine/projectchaplin/api/node_modules/@dadi/api/dadi/lib/model/connection.js:111:27)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"msg":"DB connection failed with connection string mongodb://mongo:27017/test?readPreference=secondaryPreferred","time":"2018-09-27T14:17:58.219Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:17:58.719Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:17:58.719Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:17:58.719Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:17:58.723Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:17:58.723Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:17:58.723Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:17:58.723Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:17:58.724Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:17:58.723Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:17:58.724Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:17:58.723Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:17:58.724Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:17:59.788Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:17:59.788Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:17:59.788Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:00.217Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:00.217Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:00.217Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:00.219Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:00.219Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:00.219Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:00.484Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:00.484Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:00.484Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:02.484Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:02.484Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:02.484Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:03.542Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:03.542Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:03.542Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:03.773Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:03.773Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:03.773Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:03.992Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:03.992Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:03.992Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:08.297Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:08.297Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:08.297Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:10.171Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:10.171Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:10.171Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:10.265Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:10.265Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:10.265Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:11.526Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:11.526Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:11.526Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:19.631Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:19.631Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":9180,"level":50,"module":"connection","msg":"{ MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]\n    at Pool.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/home/dwd/code/mine/projectchaplin/api/node_modules/mongodb-core/lib/connection/connection.js:189:49)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoError',\n  message:\n   'failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo EAI_AGAIN mongo mongo:27017]' }","time":"2018-09-27T14:18:19.631Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":21146,"level":30,"module":"router","msg":"GET / 404 1ms","time":"2018-09-27T14:34:23.655Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":21146,"level":30,"module":"router","msg":"GET /status 404 1ms","time":"2018-09-27T14:34:29.800Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":21146,"level":30,"module":"router","msg":"GET /1.0/chaplin/users 404 0ms","time":"2018-09-27T14:34:40.370Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":21146,"level":30,"module":"router","msg":"GET /1.0/chaplin/tokenStore 404 0ms","time":"2018-09-27T14:34:49.531Z","v":0}
{"name":"dadi-api","hostname":"gliese","pid":21146,"level":30,"module":"router","msg":"GET /1.0/test/tokenStore 404 0ms","time":"2018-09-27T14:34:56.568Z","v":0}
